/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config = 
{
  address: '0.0.0.0',
  port: 8082,
  ipWhitelist: [
    '127.0.0.1',
    '::ffff:127.0.0.1',
    '::1',
    '::ffff:192.168.35.1',
    '::ffff:192.168.35.254',
    '192.168.35.1/24',
    '255.255.255.255',
    '0,0,0,0',
    'x,x,x,x'
  ],
  language: 'kr',
  modules: [
    {
      module: 'MMM-Detector',
      position: 'top_right',
      classes: 'always',
      configDeepMerge: true,
      config: {
        useLogos: false,
        detectors: [
          {
            detector: 'Snowboy',
            Model: 'jarvis',
            Sensitivity: null,
            Logo: 'google',
            autoRestart: false,
            onDetected: {
              notification: 'GA_ACTIVATE'
            }
          }
        ]
      },
      header: ''
    },
    {
      module: 'MMM-GoogleAssistant',
      position: 'top_left',
      configDeepMerge: true,
      config: {
        assistantConfig: {
          lang: 'ko-KR',
          latitude: 36.6291558,
          longitude: 127.4563079
        },
        responseConfig: {
          useFullscreen: false,
          useResponseOutput: true,
          responseOutputCSS: 'response_output.css',
          screenOutputTimer: 5000,
          activateDelay: 250,
          useAudioOutput: true,
          useChime: true,
          confirmationChime: true,
          useInformations: true,
          chimes: {
            beep: 'beep.mp3',
            error: 'error.mp3',
            continue: 'continue.mp3',
            confirmation: 'confirmation.mp3',
            open: 'Google_beep_open.mp3',
            close: 'Google_beep_close.mp3',
            warning: 'warning.ogg'
          },
          imgStatus: {
            confirmation: 'confirmation.gif',
            listen: 'listen.gif',
            error: 'error.gif',
            reply: 'reply.gif',
            standby: 'standby.gif'
          },
          zoom: {
            transcription: '80%',
            responseOutput: '60%'
          }
        },
        micConfig: {},
        Extented: {
          useEXT: true,
          deviceName: 'SmartMirror',
          stopCommand: '정지',
          youtube: {
            useYoutube: true,
            youtubeCommand: '유튜브',
            displayResponse: true,
            useVLC: true,
            minVolume: 30,
            maxVolume: 100
          },
          links: {
            useLinks: false,
            displayDelay: 60000,
            scrollActivate: true,
            scrollStep: 25,
            scrollInterval: 1000,
            scrollStart: 5000
          },
          photos: {},
          volume: {},
          welcome: {
            useWelcome: false,
            welcome: 'brief today'
          },
          screen: {
            useScreen: true,
            animateBody: true,
            delay: 300000,
            turnOffDisplay: false,
            mode: 1,
            ecoMode: false,
            delayed: 0,
            displayCounter: false,
            displayBar: true,
            displayStyle: 'Text',
            detectorSleeping: false,
            governorSleeping: false,
            displayLastPresence: true,
            userPresenceNotification: true,
            screenStatusNotification: true
          },
          touch: {},
          pir: {},
          governor: {},
          internet: {
            useInternet: true,
            displayPing: false,
            delay: 120000,
            scan: 'google.kr',
            command: 'pm2 restart 0',
            showAlert: true,
            needRestart: false
          },
          cast: {
            useCast: true,
            castName: 'Magic Mirror (Vanity)',
            port: 8569
          },
          spotify: {
            useSpotify: false,
            visual: {
              updateInterval: 1000,
              idleInterval: 10000,
              useBottomBar: false,
              CLIENT_ID: '',
              CLIENT_SECRET: ''
            },
            player: {}
          }
        }
      },
      header: ''
    },
    {
      module: 'clock',
      position: 'top_left',
      classes: 'always',
      config: {
        classes: 'always'
      }
    },
    {
      module: 'compliments',
      position: 'lower_third',
      classes: 'unknown',
      config: {
        compliments: {
          anytime: [
            '사용자 등록을 완료하세요'
          ]
        }
      }
    },
    {
      module: 'currentweather',
      position: 'top_left',
      header: '',
      classes: 'Billgates Robert',
      config: {
        location: 'Cheongju, KR',
        locationID: '1845604',
        appid: '62eeac7286c33c29902a61152108799f'
      }
    },
    {
      module: 'MMM-AirQuality',
      position: 'top_left',
      header: '대기오염',
      classes: 'Billgates',
      config: {
        location: 'cheongju'
      }
    },
    {
      module: 'MMM-WeatherOrNot',
      disabled: false,
      position: 'top_left',
      header: '',
      classes: 'Billgates Robert',
      config: {
        location: 'cheongju-si',
        locationCode: '36d64127d49',
        languages: 'en',
        tempUnits: 'C',
        font: 'Tahoma',
        textColor: '#ffffff',
        htColor: '#ffffff',
        ltColor: '#00dfff',
        sunColor: '#febc2f',
        moonColor: '#dfdede',
        cloudColor: '#dfdede',
        cloudFill: '#1f567c',
        rainColor: '#93bffe',
        snowColor: '#dfdede',
        height: '220px',
        width: '350px',
        label: 'New Dorp',
        label2: 'Staten Island',
        days: '7',
        theme: 'dark',
        bgColor: '#000000',
        icons: 'Climacons Animated',
        updateInterval: 600000
      }
    },
    {
      module: 'calendar_monthly',
      position: 'top_center',
      header: '',
      classes: 'Biden Robert',
      config: {}
    },
    {
      module: 'calendar',
      header: 'calendar_Detail',
      classes: 'Biden',
      position: 'top_center',
      config: {
        calendars: [
          {
            symbol: 'calendar-check',
            url: 'https://calendar.google.com/calendar/ical/cbnugrade%40gmail.com/private-2c50420b8f6a3dd4d807573635366158/basic.ics'
          }
        ]
      }
    },
    {
      module: 'MMM-Face-Reco-DNN',
      classes: 'always',
      config: {}
    },
    {
      module: 'Face-Reco-Multi-Users',
      position: 'top_right',
      classes: 'always',
      config: {
        useMMMFaceRecoDNN: true
      }
    },
    {
      module: 'MMM-NewsFeed',
      position: 'top_right',
      configDeepMerge: true,
      classes: 'Billgates',
      config: {
        flux: [
          {
            from: '실시간 뉴스',
            url: 'https://www.yonhapnewstv.co.kr/browse/feed/',
            encoding: 'UTF-8'
          }
        ]
      }
    },
    {
      module: 'MMM-cryptocurrency',
      position: 'top_right',
      classes: 'Biden',
      config: {
        apikey: '6bab2f3d-5658-4e19-802c-498573b55ecb',
        currency: [
          'ethereum',
          'bitcoin',
          'xrp'
        ],
        conversion: 'KRW',
        headers: [
          'change24h',
          'change1h',
          'change7d'
        ],
        displayType: 'logo',
        fontSize: 'small',
        showGraphs: true
      }
    },
    {
      module: 'MMM-Remote-Control',
      position: 'bottom_right',
      classes: 'always',
      config: {
        showModuleApiMenu: true,
        secureEndpoints: true,
        pm2ProcessName: 'MagicMirror'
      }
    }
  ],
  useHttps: false,
  httpsPrivateKey: '',
  httpsCertificate: ''
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
